### ISSUE TITLE
Filters are lost when container list changes

### ISSUE THREAD

**Issue by rocketraman** [TomasTomecek/sen#85] opened 2016-05-14 19:43 UTC
When I have a filter `s=r` set in sen, when the container list changes while on a different tab e.g. a container details tab, the filter is still set but the list is no longer filtered.

I am running the dev version, but this is an issue on the stable version as well.

**Comment by TomasTomecek** [comment] 2016-05-15 18:10
I also experienced that filters are a bit clunky when mixed with other  operations but didn't have a chance to open an issue, so thanks for doing so! 

Right now I'm in process of significant rewrite of command system. Once that's done, I'll take a look in this.

**Comment by TomasTomecek** [comment] 2016-05-28 20:38
this should be fixed in master now (had to rewrite it much); haven't tested extensively, will close this once 0.4 is out

**Comment by rocketraman** [comment] 2016-05-31 00:42
> this should be fixed in master now (had to rewrite it much); haven't tested extensively, will close this once 0.4 is out

It's definitely better. The filter now stays active. However, now I am seeing the filtered list does not update when the list of containers changes e.g. a container is stopped and a new one started with an updated image. The filtered list just keeps the old container listed. I do have the container open in a "detail" tab -- not sure if that makes a difference.

**Comment by TomasTomecek** [comment] 2016-05-31 07:31
looks like that filtering needs even more care; before doing final release, I'll take care of this

**Comment by TomasTomecek** [comment] 2016-06-15 13:27
Found it, finally! If an image had multiple names, only the first one was taken into account. So now, all names are being considered.

Could you please retest with master? If it doesn't work, I would appreciate detailed steps to reproduce since this is getting pretty complex.

I tested like this: I applied filter `asdqwe`. In other terminal I kept creating/removing containers with name `asdqwe` and I kept tagging and untagging an image with name `asdqwe`. The interface was being continuously updated and only correct objects were displayed.

**Comment by TomasTomecek** [comment] 2016-06-29 13:01
This should be fixed in `0.4.0`

**Closed by TomasTomecek** 2016-06-29 13:01 UTC
Labels: bug, fixed-in-master
