### ISSUE TITLE
UnicodeEncodeError when viewing docker logs

### ISSUE THREAD

**Issue by dustymabe** [TomasTomecek/sen#23] opened 2015-10-24 16:08 UTC
Somehow I ended up with this on screen:

```
2015-10-24 16:05:41,168 - sen - ERROR - Exception caught: UnicodeEncodeError('ascii', '\u251c\u2500\u2500 lodash@2.4.2', 0, 3, 'ordinal not in range(128)')
```

I wish I had more info, or even a stack trace but that is it, sorry.

**Comment by TomasTomecek** [comment] 2015-10-26 08:58
Am going to fix.

**Comment by TomasTomecek** [comment] 2015-10-26 11:21
I can't reproduce: `docker logs` behaves differently between 1.8 and 1.9. Therefore there may be a regression (in engine, or docker-py).

I can probably tell where the exception occurred so I'll try to fortify that code and write some simple tests.

**Comment by TomasTomecek** [comment] 2015-10-27 07:43
This should be resolved in master by https://github.com/TomasTomecek/sen/commit/0412ee72bacd9ee37a35a1360390c7af6eaf56eb and  verified by tests in https://github.com/TomasTomecek/sen/commit/d58b3e06f7af1b7e443a167bf9e0c7a836090573. Feel free to reopen if you encounter this again. Thanks for report.

**Closed by TomasTomecek** 2015-10-27 07:43 UTC
Labels: bug
